= JGitflow Gradle Plugin
:author: Robert Winkler
:version: 0.1.0
:hardbreaks:

image:https://travis-ci.org/RobWin/jgitflow-gradle-plugin.svg["Build Status", link="https://travis-ci.org/RobWin/jgitflow-gradle-plugin"] image:https://coveralls.io/repos/RobWin/jgitflow-gradle-plugin/badge.svg["Coverage Status", link="https://coveralls.io/r/RobWin/jgitflow-gradle-plugin"] image:http://img.shields.io/badge/license-ASF2-blue.svg["Apache License 2", link="http://www.apache.org/licenses/LICENSE-2.0.txt"] image:https://img.shields.io/badge/Twitter-rbrtwnklr-blue.svg["Twitter", link="https://twitter.com/rbrtwnklr"]

== Overview

This is a JGitflow Gradle Plugin which supports the Gitflow Workflow. It uses `org.eclipse.jgit` and `com.atlassian.jgitflow:jgit-flow-core` to implement the Gitflow Workflow. The project is inspired by the http://jgitflow.bitbucket.org/[JGitFlow Maven Plugin].
The Plugin adds the following tasks under a group called "jgitflow":

* releaseStart: creates a release branch and updates the gradle.properties file with a release version
* releaseFinish: merges the release branch with the master branch and develop branch

== Usage guide

Add the following snippet to your Gradle build file:

[source,groovy]
[subs="attributes"]
----
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'io.github.robwin:jgitflow-gradle-plugin:{version}'
    }
}

apply plugin: 'io.github.robwin.jgitflow'
----

The default Gitflow configuration looks as follows:

.Branch names
[options="header"]
|===
|Logical branch name | Real branch name
|master | "master"
|develop | "develop"
|feature | "feature/<featureName>"
|release | "release/<releaseVersion>"
|hotfix | "hotfix/<hotfixName>";
|===

By default the release tag has no version prefix.

=== Release Start Task

The plugin adds a task named `releaseStart`. The task checks that the current project version is a snapshot version, e.g. `1.0.0-SNAPSHOT`, and that no snapshot library dependencies are used.
It creates a release branch `releases/<releaseVersion>` and updates the `gradle.properties` file with a release version.
The task exposes a few properties as part of its configuration.

.Properties of releaseStart
[options="header"]
|===
|Property | Description | Type | Default
|releaseVersion | The version of the release |  String | empty
|allowSnapshotDependencies| Allow snapshot library dependencies | Boolean| false
|===

==== Example

The tasks should be invoked via a command line.

`gradlew releaseStart -PreleaseVersion=1.0.0`

== License

Copyright 2015 Robert Winkler

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
