= JGitflow Gradle Plugin
:author: Robert Winkler
:version: 0.2.0
:hardbreaks:

image:https://travis-ci.org/RobWin/jgitflow-gradle-plugin.svg["Build Status", link="https://travis-ci.org/RobWin/jgitflow-gradle-plugin"] image:https://coveralls.io/repos/RobWin/jgitflow-gradle-plugin/badge.svg["Coverage Status", link="https://coveralls.io/r/RobWin/jgitflow-gradle-plugin"] image:https://api.bintray.com/packages/robwin/maven/jgitflow-gradle-plugin/images/download.svg[link="https://bintray.com/robwin/maven/jgitflow-gradle-plugin/_latestVersion"] image:http://img.shields.io/badge/license-ASF2-blue.svg["Apache License 2", link="http://www.apache.org/licenses/LICENSE-2.0.txt"] image:https://img.shields.io/badge/Twitter-rbrtwnklr-blue.svg["Twitter", link="https://twitter.com/rbrtwnklr"] image:https://badges.gitter.im/Join%20Chat.svg[link="https://gitter.im/RobWin/jgitflow-gradle-plugin?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]

== Overview

This is a Gradle Plugin which adds tasks to Gradle to support the https://de.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow/[Gitflow Workflow]. The Gitflow Workflow provides a robust framework for managing larger projects. The Plugin uses `org.eclipse.jgit` and `external.atlassian.jgitflow:jgit-flow-core` to implement the Gitflow Workflow. The project is inspired by the http://jgitflow.bitbucket.org/[JGitFlow Maven Plugin].
The Plugin adds a task group `jgitflow` which contains the following tasks:

* `releaseStart`: Creates a release branch `release/<releaseVersion>` and updates the gradle.properties file with a release version.
* `releaseFinish`: Merges a release branch back into the master branch and develop branch and pushes everything to the remote origin.
* `releasePublish`: Publishes a release branch to the remote origin.
* `featureStart`: Creates a feature branch `feature/<featureName>`.
* `featureFinish`: Merges a feature branch back into the develop branch.
* `featurePublish`: Publishes a feature branch to the remote origin.
* `hotfixStart`: Creates a hotfix branch `hotfix/<hotfixName>`.
* `hotfixFinish`: Merges a hotfix branch back into the master branch and develop branch.
* `hotfixPublish`: Publishes a hotfix branch to the remote origin.

The project requires at least JDK 7.

== Usage Guide

Add the following snippet to your Gradle build file:

[source,groovy]
[subs="attributes"]
----
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'io.github.robwin:jgitflow-gradle-plugin:{version}'
    }
}

apply plugin: 'io.github.robwin.jgitflow'
----

The default `jgitflow` configuration looks as follows:

.Branch names
[options="header"]
|===
|Logical branch name | Real branch name
|master | "master"
|develop | "develop"
|feature | "feature/<featureName>"
|release | "release/<releaseVersion>"
|hotfix | "hotfix/<hotfixName>";
|===

By default a release tag has no version prefix.

=== Release Start Task

The task `releaseStart` checks that no snapshot library dependencies are used. It creates a release branch `release/<releaseVersion>` and updates the `gradle.properties` file with a release version.
The task exposes a few properties as part of its configuration.

.Properties of releaseStart
[options="header"]
|===
|Mandatory |Property | Description | Type | Default
|Yes |releaseVersion | The version of the release |  String | empty
|No |allowSnapshotDependencies| Allow snapshot library dependencies | Boolean| false
|No |baseCommit| You can optionally supply a base commit sha-1 hash to start the release from. The commit must be on the develop branch. | String| empty
|===

==== Example

The tasks should be invoked via a command line.

`gradlew releaseStart -PreleaseVersion=1.0.0`

=== Release Finish Task

The task `releaseFinish` merges the release branch into the master branch and develop branch.

==== Example

The tasks should be invoked via a command line.

`gradlew releaseFinish -PreleaseVersion=1.0.0`

== License

Copyright 2015 Robert Winkler

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
